### ISSUE TITLE
Trying to setup it up

### ISSUE THREAD

**Issue by tczee36** [vtnerd/motrix#4]
Hello,

Thanks for making this cool project.

Im trying to compile it , running to an error
xmr@xmr-node:~/motrix$ ls
aclocal.m4  autom4te.cache  configure  configure.ac  depcomp  Dockerfile  external  install-sh  LICENSE  Makefile.am  Makefile.in  missing  README.md  src
xmr@xmr-node:~/motrix$ mkdir build && cd build
xmr@xmr-node:~/motrix/build$ sudo CXXFLAGS="-O2 -DNDEBUG" ../configure && make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking c++11 enable-if type traits... yes
checking c++11 variadic template support... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zmq.h usability... no
checking zmq.h presence... no
checking for zmq.h... no
configure: error: Unable to find ZeroMQ header
xmr@xmr-node:~/motrix/build$ 

> xmr@xmr-node:~/motrix$ ls
aclocal.m4  autom4te.cache  configure  configure.ac  depcomp  Dockerfile  external  install-sh  LICENSE  Makefile.am  Makefile.in  missing  README.md  src
xmr@xmr-node:~/motrix$ mkdir build && cd build
xmr@xmr-node:~/motrix/build$ sudo CXXFLAGS="-O2 -DNDEBUG" ../configure && make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking c++11 enable-if type traits... yes
checking c++11 variadic template support... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zmq.h usability... no
checking zmq.h presence... no
checking for zmq.h... no
configure: error: Unable to find ZeroMQ header
xmr@xmr-node:~/motrix/build$

**Comment by westz36** [comment]
xmr@xmr-node:~/motrix$ ls
aclocal.m4  autom4te.cache  configure  configure.ac  depcomp  Dockerfile  external  install-sh  LICENSE  Makefile.am  Makefile.in  missing  README.md  src
xmr@xmr-node:~/motrix$ mkdir build && cd build
xmr@xmr-node:~/motrix/build$ sudo CXXFLAGS="-O2 -DNDEBUG" ../configure && make
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking c++11 enable-if type traits... yes
checking c++11 variadic template support... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zmq.h usability... no
checking zmq.h presence... no
checking for zmq.h... no
**_### configure: error: Unable to find ZeroMQ header_**
xmr@xmr-node:~/motrix/build$

**Comment by tczee36** [comment]
fixed it

was missing dependencies

specifically:

 sudo apt-get install libncurses5-dev libncursesw5-dev

and libzmq-java or something similar to libzmq*
